version: '3.4'

services:
  db:
    image: postgres:10.6-alpine
    env_file: .env
    ports:
      - '5432:5432'
  hasura:
    image: hasura/graphql-engine:v1.0.0.cli-migrations
    ports:
      - '8080:8080'
    depends_on:
      - "db"
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
    env_file: .env
  pgadmin:
    image: dpage/pgadmin4:4.17
    env_file: .env
    ports:
      - "5400:80"
    # Tried to predefine the DB server, which didn't work well on Windows
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
#    volumes:
#      - "./utils/pgadmin-servers.json:/servers.json"
